import pickle
import random

from contracts import evaluate_contract, generate_contracts
from exploit_system import generate_run_exploit_catalog
from runtime_paths import resolve_user_data_path


class ThreatLedger:
    def __init__(self):
        # Tracks the "Noise" generated by the player's playstyle
        self.brute_force_noise = 0
        self.exploit_noise = 0
        self.stealth_noise = 0

    def add_noise(self, category: str, amount: int):
        if category == "brute_force":
            self.brute_force_noise += amount
        elif category == "exploit":
            self.exploit_noise += amount

    def get_primary_threat(self) -> str:
        """Determines what the network thinks the player is doing."""
        if self.brute_force_noise == 0 and self.exploit_noise == 0:
            return "unknown"

        if self.brute_force_noise >= self.exploit_noise:
            return "brute_force"
        else:
            return "exploit"


class GameState:
    def __init__(self):
        self.threat_ledger = ThreatLedger()
        self.player_crypto = 0
        self.trace_level = 0
        self.day = 1
        self.game_over = False
        self.prologue_complete = False
        self.origin_story = "rookie"
        self.run_seed = random.randint(10_000, 999_999)
        self.exploit_catalog = generate_run_exploit_catalog(self.run_seed)
        self.known_exploit_ids = [
            exploit["id"] for exploit in self.exploit_catalog if exploit.get("known_at_start")
        ]
        self.encounter_script_log = []
        self.encounter_triggered_exploits = []
        self.current_contracts = []
        self.contract_history = []

    @staticmethod
    def resolve_save_path(filename="save_data.pkl"):
        return str(resolve_user_data_path(filename))

    def ensure_runtime_defaults(self):
        if not hasattr(self, "prologue_complete"):
            self.prologue_complete = True
        if not hasattr(self, "origin_story"):
            self.origin_story = "rookie"
        if not hasattr(self, "run_seed"):
            self.run_seed = random.randint(10_000, 999_999)
        if not hasattr(self, "exploit_catalog") or not self.exploit_catalog:
            self.exploit_catalog = generate_run_exploit_catalog(self.run_seed)
        if not hasattr(self, "known_exploit_ids"):
            self.known_exploit_ids = [
                exploit["id"] for exploit in self.exploit_catalog if exploit.get("known_at_start")
            ]
        else:
            known = list(dict.fromkeys(self.known_exploit_ids))
            for exploit in self.exploit_catalog:
                if exploit.get("known_at_start") and exploit["id"] not in known:
                    known.append(exploit["id"])
            self.known_exploit_ids = known
        if not hasattr(self, "encounter_script_log"):
            self.encounter_script_log = []
        if not hasattr(self, "encounter_triggered_exploits"):
            self.encounter_triggered_exploits = []
        if not hasattr(self, "current_contracts"):
            self.current_contracts = []
        if not hasattr(self, "contract_history"):
            self.contract_history = []

    def reset_run_signatures(self):
        self.run_seed = random.randint(10_000, 999_999)
        self.exploit_catalog = generate_run_exploit_catalog(self.run_seed)
        self.known_exploit_ids = [
            exploit["id"] for exploit in self.exploit_catalog if exploit.get("known_at_start")
        ]
        self.begin_encounter_tracking()
        self.current_contracts = []
        self.contract_history = []

    def begin_encounter_tracking(self):
        self.encounter_script_log = []
        self.encounter_triggered_exploits = []

    def issue_world_contracts(self, world):
        if self.current_contracts:
            archived = [dict(contract) for contract in self.current_contracts]
            self.contract_history.extend(archived)
        self.current_contracts = generate_contracts(self.run_seed, self.day, world)

    def get_contract_by_id(self, contract_id: str):
        for contract in self.current_contracts:
            if contract.get("id") == contract_id:
                return contract
        return None

    def accept_contract(self, contract_id: str):
        contract = self.get_contract_by_id(contract_id)
        if not contract or contract.get("completed") or contract.get("failed"):
            return False
        contract["accepted"] = True
        return True

    def get_accepted_contracts(self):
        return [
            contract
            for contract in self.current_contracts
            if contract.get("accepted") and not contract.get("completed") and not contract.get("failed")
        ]

    def get_contracts_for_node(self, ip_address: str, *, accepted_only=False):
        contracts = self.current_contracts
        if accepted_only:
            contracts = self.get_accepted_contracts()
        return [contract for contract in contracts if contract.get("target_ip") == ip_address]

    def resolve_contracts_for_node(self, node, enemy, encounter_report):
        messages = []
        for contract in self.get_contracts_for_node(node.ip_address, accepted_only=True):
            passed, failure_reason = evaluate_contract(contract, node, enemy, encounter_report)
            if passed:
                contract["completed"] = True
                reward = contract.get("reward", 0)
                self.player_crypto += reward
                messages.append(
                    f"[CONTRACT COMPLETE] {contract['subject']} // payout {reward} Crypto transferred."
                )
            else:
                contract["failed"] = True
                messages.append(
                    f"[CONTRACT FAILED] {contract['subject']} // {failure_reason}."
                )
        return messages

    def get_known_exploits(self):
        known_ids = set(self.known_exploit_ids)
        return [
            exploit
            for exploit in self.exploit_catalog
            if exploit.get("known_at_start") or exploit["id"] in known_ids
        ]

    def get_unknown_exploit_count(self):
        return max(0, len(self.exploit_catalog) - len(self.get_known_exploits()))

    def get_tutorial_exploit(self):
        for exploit in self.exploit_catalog:
            if exploit.get("tutorial"):
                return exploit
        return self.exploit_catalog[0] if self.exploit_catalog else None

    def register_exploit_event(self, parsed_command, script_data: dict, resolved_target: str | None, enemy, player, *, source="player"):
        event = {
            "script": parsed_command.base_cmd,
            "target": resolved_target,
            "flags": list(parsed_command.flags),
            "type": script_data.get("type", "unknown"),
            "source": source,
        }
        self.encounter_script_log.append(event)
        self.encounter_script_log = self.encounter_script_log[-10:]

        for exploit in sorted(self.exploit_catalog, key=lambda item: len(item.get("sequence", [])), reverse=True):
            if exploit.get("phase") not in {None, "combat", "any"}:
                continue
            if exploit["id"] in self.encounter_triggered_exploits:
                continue
            if not self._matches_exploit(exploit, enemy):
                continue
            self.encounter_triggered_exploits.append(exploit["id"])
            return self._activate_exploit(exploit, enemy, player)

        return None

    def _matches_exploit(self, exploit: dict, enemy) -> bool:
        steps = exploit.get("sequence", [])
        if len(self.encounter_script_log) < len(steps):
            return False

        tail = self.encounter_script_log[-len(steps) :]
        for step, event in zip(steps, tail):
            if step.get("script") != event.get("script"):
                return False
            target = step.get("target")
            if target is not None and target != event.get("target"):
                return False

        condition = exploit.get("condition", {})
        condition_type = condition.get("type", "any")
        if condition_type == "security_open":
            return enemy.subsystems["SEC"].is_destroyed or enemy.security_breach_turns > 0
        if condition_type == "intent_revealed":
            return enemy.intent_revealed
        if condition_type == "target_below_ratio":
            target_ref = condition.get("target_ref", "same")
            if target_ref == "same":
                target_key = tail[-1].get("target")
            else:
                target_key = target_ref
            if target_key not in enemy.subsystems:
                return False
            target = enemy.subsystems[target_key]
            ratio = target.current_hp / max(1, target.max_hp)
            return ratio <= condition.get("ratio", 0.5)
        if condition_type == "signature_hidden":
            return not enemy.player_signature_revealed
        return True

    def _activate_exploit(self, exploit: dict, enemy, player):
        effect = exploit.get("effect", {})
        lines = []
        discovered = False
        if exploit["id"] not in self.known_exploit_ids:
            self.known_exploit_ids.append(exploit["id"])
            discovered = True

        header = "[EXPLOIT DISCOVERED]" if discovered else "[EXPLOIT TRIGGERED]"
        lines.append(f"\033[95m{header}\033[0m {exploit['name']} :: {exploit['sequence_text']}")

        bonus_damage = effect.get("bonus_damage", 0)
        if bonus_damage > 0:
            damage_target = effect.get("damage_target", "OS")
            if damage_target == "same":
                damage_target = self.encounter_script_log[-1].get("target") or "OS"
                if damage_target not in enemy.subsystems or enemy.subsystems[damage_target].is_destroyed:
                    damage_target = "OS"
            target = enemy.subsystems.get(damage_target, enemy.subsystems["OS"])
            dealt = target.take_damage(bonus_damage)
            if dealt > 0:
                lines.append(f"         Bonus payload ruptured [{damage_target}] for {dealt} damage.")
                if target.is_destroyed and damage_target != "OS":
                    cascade = enemy.subsystems["OS"].take_damage(2)
                    if cascade > 0:
                        lines.append(f"         Collapse cascade rattled Core OS for {cascade}.")

        extend_breach = effect.get("extend_breach", 0)
        if extend_breach > 0:
            enemy.security_breach_turns = max(enemy.security_breach_turns, extend_breach + enemy.security_breach_turns)
            lines.append(f"         Firewall disruption extended by {extend_breach} turn(s).")

        ram_refund = effect.get("ram_refund", 0)
        if ram_refund > 0:
            player.current_ram = min(player.get_effective_max_ram(), player.current_ram + ram_refund)
            lines.append(f"         Route optimizer refunded {ram_refund} RAM.")

        trace_reduction = effect.get("trace_reduction", 0)
        if trace_reduction > 0:
            old_trace = self.trace_level
            self.trace_level = max(0, self.trace_level - trace_reduction)
            lines.append(f"         Trace pressure fell by {old_trace - self.trace_level}.")

        crypto_gain = effect.get("crypto_gain", 0)
        if crypto_gain > 0:
            self.player_crypto += crypto_gain
            lines.append(f"         Cache bleed siphoned {crypto_gain} Crypto.")

        if effect.get("reveal_weakness"):
            enemy.weakness_revealed = True
            lines.append(f"         Weak point auto-fingerprinted: [{enemy.weakness}].")

        if effect.get("recon_reset"):
            enemy.player_signature_revealed = False
            enemy.player_topology_revealed = False
            player.signature_revealed = False
            player.topology_exposed = False
            lines.append("         Hostile recon lock burned back to cold.")

        if effect.get("expose_intent"):
            enemy.intent_revealed = True
            lines.append("         Hostile process chatter is now readable.")

        stun_turns = effect.get("stun_turns", 0)
        if stun_turns > 0:
            enemy.intent_jam_turns = max(getattr(enemy, "intent_jam_turns", 0), stun_turns)
            lines.append(f"         Signal jam queued. Hostile turn stalled for {stun_turns} round(s).")

        return {
            "exploit": exploit,
            "discovered": discovered,
            "lines": lines,
        }

    @staticmethod
    def save_session(state, player, filename="save_data.pkl"):
        """Handles the serialization of the game session to keep data logic out of the UI."""
        save_path = GameState.resolve_save_path(filename)
        save_dir = resolve_user_data_path(filename).parent
        save_dir.mkdir(parents=True, exist_ok=True)
        with open(save_path, "wb") as f:
            pickle.dump({"state": state, "player": player}, f)

    @staticmethod
    def delete_session(filename="save_data.pkl"):
        save_path = GameState.resolve_save_path(filename)
        save_file = resolve_user_data_path(filename)
        if save_file.exists():
            save_file.unlink()

    @staticmethod
    def load_session(filename="save_data.pkl"):
        """Loads a previously saved game session."""
        save_path = GameState.resolve_save_path(filename)
        if resolve_user_data_path(filename).exists():
            with open(save_path, "rb") as f:
                return pickle.load(f)
        return None
